"""widen currency column

Revision ID: 03ea559c9f33
Revises: 44bbbe0862ad
Create Date: 2026-04-12 22:59:17.625474
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '03ea559c9f33'
down_revision: Union[str, None] = '44bbbe0862ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contracts', 'currency',
               existing_type=sa.VARCHAR(length=3),
               type_=sa.String(length=10),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contracts', 'currency',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=3),
               existing_nullable=False)
    # ### end Alembic commands ###
