"""add auto release fields

Revision ID: 44bbbe0862ad
Revises: a12ee730c52f
Create Date: 2026-04-09 20:23:14.911909
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '44bbbe0862ad'
down_revision: Union[str, None] = 'a12ee730c52f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('auto_release_days', sa.Integer(), nullable=True))
    op.execute("UPDATE contracts SET auto_release_days = 7 WHERE auto_release_days IS NULL")
    op.alter_column('contracts', 'auto_release_days', nullable=False)
    op.add_column('milestones', sa.Column('auto_release_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('milestones', 'auto_release_at')
    op.drop_column('contracts', 'auto_release_days')
    # ### end Alembic commands ###
