"""add waitlist

Revision ID: a12ee730c52f
Revises: 43f52db6418e
Create Date: 2026-04-09 20:15:41.792173
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'a12ee730c52f'
down_revision: Union[str, None] = '43f52db6418e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waitlist',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('CLIENT', 'FREELANCER', 'BOTH', name='waitlistrole'), nullable=False),
    sa.Column('referral_source', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waitlist_email'), 'waitlist', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_waitlist_email'), table_name='waitlist')
    op.drop_table('waitlist')
    # ### end Alembic commands ###
